### ISSUE TITLE
Adding "fire" time

### ISSUE THREAD

**Issue by leikoilja** [DurgNomis-drol/ha-google-home-timers-card#1]
Thanks for a great card, @DurgNomis-drol! 💥 

I like the design of it! Pretty cool that you show how much time is left and the duration of the timer. Would it be useful to add the time when the alarm will go off? 

Perhaps it can be an optional setting? So when you add a card you can say something like
```yaml
type: 'custom:googletimers-card'
entity: sensor.kitchen_timers
show_fire_time: true
title: My own title
```

And it will show the full time when it will go off on the card, for example "18:30:00"?
